- name: Automatic Changelog Generator
  # You may pin to the exact commit or the version.
  # uses: charmixer/auto-changelog-action@b25e89c9410e03189f0d48b02b3a8caad6e78015
  uses: charmixer/auto-changelog-action@v1.4
  with:
    # Username of the owner of target GitHub repo (default: extracted from $GITHUB_REPOSITORY)
    user: # optional
    # Name of project on GitHub (default: extracted from $GITHUB_REPOSITORY)
    project: # optional
    # Limit pull requests to the release branch, such as master or release (required, default: master)
    release_branch: # optional, default is master
    # Output file. To print to STDOUT instead, use blank as path. (required, default: CHANGELOG.md)
    output: # optional, default is CHANGELOG.md
    # Optional base file to append generated changes to (default: HISTORY.md)
    base: # optional
    # To make more than 50 requests per hour your GitHub token is required. You can generate it at: https://github.com/settings/tokens/new<Paste>
    token: # optional
    # Changelog will start after specified tag.
    since_tag: # optional
    # Changelog will end before specified tag.
    due_tag: # optional
    # Changelog will exclude specified tags (comma seperated)
    exclude_tags: # optional
    # Issues with the specified labels will be excluded from changelog. Default is "duplicate,question,invalid,wontfix".
    exclude_labels: # optional
    # Date format. Default is %Y-%m-%d
    date_format: # optional
    # Put the unreleased changes in the specified release number.
    future_release: # optional
    # The specified labels will be shown in brackets next to each matching issue. Use "ALL" to show all labels. Default is [].
    issue_line_labels: # optional
    # The Enterprise GitHub site where your project is hosted if using GitHub Enterprise.
    github_site: # optional
    # The enterprise endpoint to use for your GitHub API if using GitHub Enterprise.
    github_api: # optional
    # Apply a regular expression on tag names so that they can be excluded, for example: --exclude-tags-regex ".*+d{1,}".
    exclude_tags_regex: # optional
